version: 2
updates:
  - package-ecosystem: npm
    directory: /atlas_frontend
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /atlas_backend
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
